/**
 * Merge Accounting API
 * The unified API for building rich integrations with multiple Accounting & Finance platforms.
 *
 * The version of the OpenAPI document: 1.0
 * Contact: hello@merge.dev
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { CurrencyEnum } from './currencyEnum';
import { PurchaseOrderLineItem } from './purchaseOrderLineItem';
import { PurchaseOrderStatusEnum } from './purchaseOrderStatusEnum';
import { RemoteData } from './remoteData';

/**
* # The PurchaseOrder Object ### Description The `PurchaseOrder` object is used to represent a company\'s purchase orders.  ### Usage Example Fetch from the `LIST PurchaseOrders` endpoint and view a company\'s purchase orders.
*/
export class PurchaseOrder {
    'id'?: string;
    /**
    * The third-party API ID of the matching object.
    */
    'remote_id'?: string | null;
    'remote_data'?: Array<RemoteData> | null;
    /**
    * The purchase order\'s status.
    */
    'status'?: PurchaseOrderStatusEnum | null;
    /**
    * The purchase order\'s issue date.
    */
    'issue_date'?: Date | null;
    /**
    * The purchase order\'s delivery date.
    */
    'delivery_date'?: Date | null;
    /**
    * The purchase order\'s delivery address.
    */
    'delivery_address'?: string | null;
    /**
    * The purchase order\'s total amount.
    */
    'total_amount'?: number | null;
    /**
    * The purchase order\'s currency.
    */
    'currency'?: CurrencyEnum | null;
    'line_items'?: Array<PurchaseOrderLineItem>;
    /**
    * When the third party\'s purchase order note was created.
    */
    'remote_created_at'?: Date | null;
    /**
    * When the third party\'s purchase order note was updated.
    */
    'remote_updated_at'?: Date | null;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "id",
            "baseName": "id",
            "type": "string"
        },
        {
            "name": "remote_id",
            "baseName": "remote_id",
            "type": "string"
        },
        {
            "name": "remote_data",
            "baseName": "remote_data",
            "type": "Array<RemoteData>"
        },
        {
            "name": "status",
            "baseName": "status",
            "type": "PurchaseOrderStatusEnum"
        },
        {
            "name": "issue_date",
            "baseName": "issue_date",
            "type": "Date"
        },
        {
            "name": "delivery_date",
            "baseName": "delivery_date",
            "type": "Date"
        },
        {
            "name": "delivery_address",
            "baseName": "delivery_address",
            "type": "string"
        },
        {
            "name": "total_amount",
            "baseName": "total_amount",
            "type": "number"
        },
        {
            "name": "currency",
            "baseName": "currency",
            "type": "CurrencyEnum"
        },
        {
            "name": "line_items",
            "baseName": "line_items",
            "type": "Array<PurchaseOrderLineItem>"
        },
        {
            "name": "remote_created_at",
            "baseName": "remote_created_at",
            "type": "Date"
        },
        {
            "name": "remote_updated_at",
            "baseName": "remote_updated_at",
            "type": "Date"
        }    ];

    static getAttributeTypeMap() {
        return PurchaseOrder.attributeTypeMap;
    }
}

