/* tslint:disable */
/* eslint-disable */
/**
 * Merge Accounting API
 * The unified API for building rich integrations with multiple Accounting & Finance platforms.
 *
 * The version of the OpenAPI document: 1.0
 * Contact: hello@merge.dev
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../../runtime';
import { JSONValue } from '../../merge_json';
import {
    AccountingAttachmentRequest,
    AccountingAttachmentRequestFromJSON,
    AccountingAttachmentRequestFromJSONTyped,
    AccountingAttachmentRequestToJSON,
} from './';


/**
 * 
 * @export
 * @interface AccountingAttachmentEndpointRequest
 */
export interface AccountingAttachmentEndpointRequest {
    /**
     * 
     * @type {AccountingAttachmentRequest}
     * @memberof AccountingAttachmentEndpointRequest
     */
    model: AccountingAttachmentRequest;
}

export function AccountingAttachmentEndpointRequestFromJSON(json: JSONValue): AccountingAttachmentEndpointRequest | undefined {
    return AccountingAttachmentEndpointRequestFromJSONTyped(json);
}

export function AccountingAttachmentEndpointRequestFromJSONTyped(json: JSONValue): AccountingAttachmentEndpointRequest | undefined {
    if ((json === undefined) || (json === null)) {
        return undefined;
    }

    return {
        
        'model': AccountingAttachmentRequestFromJSON(json['model']) as AccountingAttachmentRequest,
    };
}

export function AccountingAttachmentEndpointRequestToJSON(value?: AccountingAttachmentEndpointRequest): JSONValue {
    if (value === undefined || value === null) {
        return undefined;
    }

    return {
        
        'model': AccountingAttachmentRequestToJSON(value.model),
    };
}

