/* tslint:disable */
/* eslint-disable */
/**
 * Merge Accounting API
 * The unified API for building rich integrations with multiple Accounting & Finance platforms.
 *
 * The version of the OpenAPI document: 1.0
 * Contact: hello@merge.dev
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import { JSONValue } from '../../merge_json'
import {
    CashFlowStatement,
    CashFlowStatementFromJSON,
    CashFlowStatementFromJSONTyped,
    CashFlowStatementToJSON,
} from './';


/**
 * 
 * @export
 * @interface PaginatedCashFlowStatementList
 */
export interface PaginatedCashFlowStatementList {
    /**
     * 
     * @type {string}
     * @memberof PaginatedCashFlowStatementList
     */
    next?: string | null;
    /**
     * 
     * @type {string}
     * @memberof PaginatedCashFlowStatementList
     */
    previous?: string | null;
    /**
     * 
     * @type {Array<CashFlowStatement>}
     * @memberof PaginatedCashFlowStatementList
     */
    results?: Array<CashFlowStatement>;
}

export function PaginatedCashFlowStatementListFromJSON(json: JSONValue): PaginatedCashFlowStatementList {
    return PaginatedCashFlowStatementListFromJSONTyped(json);
}

export function PaginatedCashFlowStatementListFromJSONTyped(json: JSONValue): PaginatedCashFlowStatementList {
    if ((json === undefined) || (json === null)) {
        return json;
    }

    return {
        
        'next': !exists(json, 'next') ? undefined : json['next'],
        'previous': !exists(json, 'previous') ? undefined : json['previous'],
        'results': !exists(json, 'results') ? undefined : ((json['results'] as Array<any>).map(CashFlowStatementFromJSON)),
    };
}

export function PaginatedCashFlowStatementListToJSON(value?: PaginatedCashFlowStatementList | null): JSONValue {
    if (value === undefined || value === null) {
        return value;
    }

    return {
        
        'next': value.next,
        'previous': value.previous,
        'results': value.results === undefined ? undefined : ((value.results as Array<any>).map(CashFlowStatementToJSON)),
    };
}

