/* tslint:disable */
/* eslint-disable */
/**
 * Merge CRM API
 * The unified API for building rich integrations with multiple CRM platforms.
 *
 * The version of the OpenAPI document: 1.0
 * Contact: hello@merge.dev
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../../runtime';
import { JSONValue } from '../../merge_json';
import {
    AccountRequest,
    AccountRequestFromJSON,
    AccountRequestFromJSONTyped,
    AccountRequestToJSON,
} from './';


/**
 * 
 * @export
 * @interface CRMAccountEndpointRequest
 */
export interface CRMAccountEndpointRequest {
    /**
     * 
     * @type {AccountRequest}
     * @memberof CRMAccountEndpointRequest
     */
    model: AccountRequest;
}

export function CRMAccountEndpointRequestFromJSON(json: JSONValue): CRMAccountEndpointRequest | undefined {
    return CRMAccountEndpointRequestFromJSONTyped(json);
}

export function CRMAccountEndpointRequestFromJSONTyped(json: JSONValue): CRMAccountEndpointRequest | undefined {
    if ((json === undefined) || (json === null)) {
        return undefined;
    }

    return {
        
        'model': AccountRequestFromJSON(json['model']) as AccountRequest,
    };
}

export function CRMAccountEndpointRequestToJSON(value?: CRMAccountEndpointRequest): JSONValue {
    if (value === undefined || value === null) {
        return undefined;
    }

    return {
        
        'model': AccountRequestToJSON(value.model),
    };
}

