/* tslint:disable */
/* eslint-disable */
/**
 * Merge CRM API
 * The unified API for building rich integrations with multiple CRM platforms.
 *
 * The version of the OpenAPI document: 1.0
 * Contact: hello@merge.dev
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../../runtime';
import { JSONValue } from '../../merge_json';
import {
    DirectionEnum,
    DirectionEnumFromJSON,
    DirectionEnumFromJSONTyped,
    DirectionEnumToJSON,
    
} from './';
import {
	RemoteData,
	RemoteDataFromJSON,
	RemoteDataFromJSONTyped,
	RemoteDataToJSON,
} from '../../remote_data';


/**
 * # The Engagement Object
 * ### Description
 * The `Engagement` object is used to represent an interaction noted in a CRM system.
 * ### Usage Example
 * TODO
 * @export
 * @interface Engagement
 */
export interface Engagement {
    /**
     * The engagement's owner.
     * @type {string}
     * @memberof Engagement
     */
    owner?: string | JSONValue | null;
    /**
     * The engagement's content.
     * @type {string}
     * @memberof Engagement
     */
    content?: string | null;
    /**
     * The engagement's subject.
     * @type {string}
     * @memberof Engagement
     */
    subject?: string | null;
    /**
     * The engagement's direction.
     * @type {DirectionEnum}
     * @memberof Engagement
     */
    direction?: DirectionEnum | null;
    /**
     * The engagement type of the engagement.
     * @type {string}
     * @memberof Engagement
     */
    engagement_type?: string | JSONValue | null;
    /**
     * The time at which the engagement started.
     * @type {Date}
     * @memberof Engagement
     */
    start_time?: Date | null;
    /**
     * The time at which the engagement ended.
     * @type {Date}
     * @memberof Engagement
     */
    end_time?: Date | null;
    /**
     * The account of the engagement.
     * @type {string}
     * @memberof Engagement
     */
    account?: string | JSONValue | null;
    /**
     * 
     * @type {Array<string>}
     * @memberof Engagement
     */
    contacts?: Array<string> | JSONValue;
    /**
     * Indicates whether or not this object has been deleted by third party webhooks.
     * @type {boolean}
     * @memberof Engagement
     */
    readonly remote_was_deleted?: boolean;
    /**
     * 
     * @type {string}
     * @memberof Engagement
     */
    readonly id?: string;
    /**
     * The third-party API ID of the matching object.
     * @type {string}
     * @memberof Engagement
     */
    remote_id?: string | null;
    /**
     * 
     * @type {{ [key: string]: any; }}
     * @memberof Engagement
     */
    readonly field_mappings?: { [key: string]: any; } | null;
    /**
     * 
     * @type {Array<RemoteData>}
     * @memberof Engagement
     */
    readonly remote_data?: Array<RemoteData> | null;
}

export function EngagementFromJSON(json: JSONValue): Engagement | undefined {
    return EngagementFromJSONTyped(json);
}

export function EngagementFromJSONTyped(json: JSONValue): Engagement | undefined {
    if ((json === undefined) || (json === null)) {
        return undefined;
    }

    return {
        
        'owner': !exists(json, 'owner') ? undefined : json['owner'],
        'content': !exists(json, 'content') ? undefined : json['content'],
        'subject': !exists(json, 'subject') ? undefined : json['subject'],
        'direction': !exists(json, 'direction') ? undefined : DirectionEnumFromJSON(json['direction']) as DirectionEnum,
        'engagement_type': !exists(json, 'engagement_type') ? undefined : json['engagement_type'],
        'start_time': !exists(json, 'start_time') ? undefined : (json['start_time'] === null ? null : new Date(json['start_time'])),
        'end_time': !exists(json, 'end_time') ? undefined : (json['end_time'] === null ? null : new Date(json['end_time'])),
        'account': !exists(json, 'account') ? undefined : json['account'],
        'contacts': !exists(json, 'contacts') ? undefined : json['contacts'],
        'remote_was_deleted': !exists(json, 'remote_was_deleted') ? undefined : json['remote_was_deleted'],
        'id': !exists(json, 'id') ? undefined : json['id'],
        'remote_id': !exists(json, 'remote_id') ? undefined : json['remote_id'],
        'field_mappings': !exists(json, 'field_mappings') ? undefined : json['field_mappings'],
        'remote_data': !exists(json, 'remote_data') ? undefined : (json['remote_data'] === null ? null : (json['remote_data'] as Array<JSONValue>).map(RemoteDataFromJSON)) as Array<RemoteData>,
    };
}

export function EngagementToJSON(value?: Engagement): JSONValue {
    if (value === undefined || value === null) {
        return undefined;
    }

    return {
        
        'owner': value.owner,
        'content': value.content,
        'subject': value.subject,
        'direction': DirectionEnumToJSON(value.direction),
        'engagement_type': value.engagement_type,
        'start_time': value.start_time === undefined ? undefined : (value.start_time === null ? null : value.start_time.toISOString()),
        'end_time': value.end_time === undefined ? undefined : (value.end_time === null ? null : value.end_time.toISOString()),
        'account': value.account,
        'contacts': value.contacts,
        'remote_id': value.remote_id,
    };
}

