/* tslint:disable */
/* eslint-disable */
/**
 * Merge CRM API
 * The unified API for building rich integrations with multiple CRM platforms.
 *
 * The version of the OpenAPI document: 1.0
 * Contact: hello@merge.dev
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { JSONValue } from "../../merge_json";

/**
 * 
 * @export
 * @enum {string}
 */
export enum IssueStatusEnum {
    MERGE_NONSTANDARD_VALUE = 'MERGE_NONSTANDARD_VALUE',
    Ongoing = 'ONGOING',
    Resolved = 'RESOLVED'
}


export function IssueStatusEnumFromJSON(json: any): IssueStatusEnum {
    return IssueStatusEnumFromJSONTyped(json, false);
}

export function IssueStatusEnumFromJSONTyped(json: any, ignoreDiscriminator: boolean): IssueStatusEnum {
    if ((<any>Object).values(IssueStatusEnum).includes(json)) {
        return json as IssueStatusEnum;
    }
    return IssueStatusEnum.MERGE_NONSTANDARD_VALUE;
}

export function IssueStatusEnumToJSON(value?: IssueStatusEnum | null): JSONValue {
    return value ? value as string : null;
}

