/* tslint:disable */
/* eslint-disable */
/**
 * Merge CRM API
 * The unified API for building rich integrations with multiple CRM platforms.
 *
 * The version of the OpenAPI document: 1.0
 * Contact: hello@merge.dev
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../../runtime';
import { JSONValue } from '../../merge_json';
import {
    CustomObjectRequest,
    CustomObjectRequestFromJSON,
    CustomObjectRequestFromJSONTyped,
    CustomObjectRequestToJSON,
} from './';


/**
 * 
 * @export
 * @interface PatchedCRMCustomObjectEndpointRequest
 */
export interface PatchedCRMCustomObjectEndpointRequest {
    /**
     * 
     * @type {CustomObjectRequest}
     * @memberof PatchedCRMCustomObjectEndpointRequest
     */
    model: CustomObjectRequest;
}

export function PatchedCRMCustomObjectEndpointRequestFromJSON(json: JSONValue): PatchedCRMCustomObjectEndpointRequest | undefined {
    return PatchedCRMCustomObjectEndpointRequestFromJSONTyped(json);
}

export function PatchedCRMCustomObjectEndpointRequestFromJSONTyped(json: JSONValue): PatchedCRMCustomObjectEndpointRequest | undefined {
    if ((json === undefined) || (json === null)) {
        return undefined;
    }

    return {
        
        'model': CustomObjectRequestFromJSON(json['model']) as CustomObjectRequest,
    };
}

export function PatchedCRMCustomObjectEndpointRequestToJSON(value?: PatchedCRMCustomObjectEndpointRequest): JSONValue {
    if (value === undefined || value === null) {
        return undefined;
    }

    return {
        
        'model': CustomObjectRequestToJSON(value.model),
    };
}

