/* tslint:disable */
/* eslint-disable */
/**
 * Merge Ticketing API
 * The unified API for building rich integrations with multiple Ticketing platforms.
 *
 * The version of the OpenAPI document: 1.0
 * Contact: hello@merge.dev
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { JSONValue } from "../../merge_json";

/**
 * 
 * @export
 * @enum {string}
 */
export enum CollectionTypeEnumValues {
    MERGE_NONSTANDARD_VALUE = 'MERGE_NONSTANDARD_VALUE',
    List = 'LIST',
    Project = 'PROJECT'
}

export interface CollectionTypeEnum {
    value: CollectionTypeEnumValues,
    rawValue: string
}


export function CollectionTypeEnumFromJSON(json: any): CollectionTypeEnum {
    return CollectionTypeEnumFromJSONTyped(json, false);
}

export function CollectionTypeEnumFromJSONTyped(json: any, ignoreDiscriminator: boolean): CollectionTypeEnum {
    if ((<any>Object).values(CollectionTypeEnumValues).includes(json)) {
        return {
            value: json as CollectionTypeEnumValues,
            rawValue: json as string
        }
    }
    return {
        value: CollectionTypeEnumValues.MERGE_NONSTANDARD_VALUE,
        rawValue: json as string
    }
}

export function CollectionTypeEnumToJSON(value?: CollectionTypeEnum | null): JSONValue {
    return value && value.value != CollectionTypeEnumValues.MERGE_NONSTANDARD_VALUE ? value.value as string : null;
}

