/* tslint:disable */
/* eslint-disable */
/**
 * Merge Ticketing API
 * The unified API for building rich integrations with multiple Ticketing platforms.
 *
 * The version of the OpenAPI document: 1.0
 * Contact: hello@merge.dev
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../../runtime';
import { JSONValue } from '../../merge_json';
import {
    Comment,
    CommentFromJSON,
    CommentFromJSONTyped,
    CommentToJSON,
    DebugModeLog,
    DebugModeLogFromJSON,
    DebugModeLogFromJSONTyped,
    DebugModeLogToJSON,
    ErrorValidationProblem,
    ErrorValidationProblemFromJSON,
    ErrorValidationProblemFromJSONTyped,
    ErrorValidationProblemToJSON,
    WarningValidationProblem,
    WarningValidationProblemFromJSON,
    WarningValidationProblemFromJSONTyped,
    WarningValidationProblemToJSON,
} from './';


/**
 * 
 * @export
 * @interface CommentResponse
 */
export interface CommentResponse {
    /**
     * 
     * @type {Comment}
     * @memberof CommentResponse
     */
    model: Comment;
    /**
     * 
     * @type {Array<WarningValidationProblem>}
     * @memberof CommentResponse
     */
    warnings: Array<WarningValidationProblem>;
    /**
     * 
     * @type {Array<ErrorValidationProblem>}
     * @memberof CommentResponse
     */
    errors: Array<ErrorValidationProblem>;
    /**
     * 
     * @type {Array<DebugModeLog>}
     * @memberof CommentResponse
     */
    logs?: Array<DebugModeLog>;
}

export function CommentResponseFromJSON(json: JSONValue): CommentResponse | null {
    return CommentResponseFromJSONTyped(json);
}

export function CommentResponseFromJSONTyped(json: JSONValue): CommentResponse | null {
    if ((json === undefined) || (json === null)) {
        return null;
    }

    return {
        
        'model': CommentFromJSON(json['model']),
        'warnings': ((json['warnings'] as Array<any>).map(WarningValidationProblemFromJSON)),
        'errors': ((json['errors'] as Array<any>).map(ErrorValidationProblemFromJSON)),
        'logs': !exists(json, 'logs') ? undefined : ((json['logs'] as Array<any>).map(DebugModeLogFromJSON)),
    };
}

export function CommentResponseToJSON(value?: CommentResponse): JSONValue {
    if (value === undefined || value === null) {
        return null;
    }

    return {
        
        'model': CommentToJSON(value.model),
        'warnings': ((value.warnings as Array<any>).map(WarningValidationProblemToJSON)),
        'errors': ((value.errors as Array<any>).map(ErrorValidationProblemToJSON)),
        'logs': value.logs === undefined ? undefined : ((value.logs as Array<any>).map(DebugModeLogToJSON)),
    };
}

