/* tslint:disable */
/* eslint-disable */
/**
 * Merge Marketing Automation API
 * The unified API for building rich integrations with multiple Marketing Automation platforms.
 *
 * The version of the OpenAPI document: 1.0
 * Contact: hello@merge.dev
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../../runtime';
import { JSONValue } from '../../merge_json';

/**
 * # The Campaign Object
 * ### Description
 * The `Campaign` object is used to represent a marketing campaign in the remote system.
 * ### Usage Example
 * Fetch from the `GET /api/mktg/v1/campaigns` endpoint and view their unique opens.
 * @export
 * @interface Campaign
 */
export interface Campaign {
    /**
     * The campaign's name.
     * @type {string}
     * @memberof Campaign
     */
    name?: string | null;
    /**
     * The campaign's unique opens.
     * @type {number}
     * @memberof Campaign
     */
    unique_opens?: number | null;
    /**
     * When the campaign was created in the remote system.
     * @type {Date}
     * @memberof Campaign
     */
    remote_created_at?: Date | null;
    /**
     * The campaign's number of emails sent.
     * @type {number}
     * @memberof Campaign
     */
    emails_sent?: number | null;
    /**
     * 
     * @type {string}
     * @memberof Campaign
     */
    readonly id?: string;
    /**
     * The third-party API ID of the matching object.
     * @type {string}
     * @memberof Campaign
     */
    remote_id?: string | null;
}

export function CampaignFromJSON(json: JSONValue): Campaign | undefined {
    return CampaignFromJSONTyped(json);
}

export function CampaignFromJSONTyped(json: JSONValue): Campaign | undefined {
    if ((json === undefined) || (json === null)) {
        return undefined;
    }

    return {
        
        'name': !exists(json, 'name') ? undefined : json['name'],
        'unique_opens': !exists(json, 'unique_opens') ? undefined : json['unique_opens'],
        'remote_created_at': !exists(json, 'remote_created_at') ? undefined : (json['remote_created_at'] === null ? null : new Date(json['remote_created_at'])),
        'emails_sent': !exists(json, 'emails_sent') ? undefined : json['emails_sent'],
        'id': !exists(json, 'id') ? undefined : json['id'],
        'remote_id': !exists(json, 'remote_id') ? undefined : json['remote_id'],
    };
}

export function CampaignToJSON(value?: Campaign): JSONValue {
    if (value === undefined || value === null) {
        return undefined;
    }

    return {
        
        'name': value.name,
        'unique_opens': value.unique_opens,
        'remote_created_at': value.remote_created_at === undefined ? undefined : (value.remote_created_at === null ? null : value.remote_created_at.toISOString()),
        'emails_sent': value.emails_sent,
        'remote_id': value.remote_id,
    };
}

