/**
 * Merge CRM API
 * The unified API for building rich integrations with multiple CRM platforms.
 *
 * The version of the OpenAPI document: 1.0
 * Contact: hello@merge.dev
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { OpportunityStatusEnum } from './opportunityStatusEnum';
import { RemoteData } from './remoteData';

/**
* # The Opportunity Object ### Description The `Opportunity` object is used to represent an opportunity in the remote system. ### Usage Example TODO
*/
export class Opportunity {
    'id'?: string;
    /**
    * The third-party API ID of the matching object.
    */
    'remote_id'?: string | null;
    /**
    * The opportunity\'s name.
    */
    'name'?: string | null;
    /**
    * The opportunity\'s description.
    */
    'description'?: string | null;
    /**
    * The opportunity\'s amount.
    */
    'amount'?: number | null;
    'owner'?: string | null;
    'account'?: string | null;
    'stage'?: string | null;
    /**
    * The opportunity\'s status.
    */
    'status'?: OpportunityStatusEnum | null;
    /**
    * When the opportunity\'s last activity occurred.
    */
    'last_activity_at'?: Date | null;
    /**
    * When the opportunity was closed.
    */
    'close_date'?: Date | null;
    /**
    * When the third party\'s opportunity was created.
    */
    'remote_created_at'?: Date | null;
    'remote_data'?: Array<RemoteData> | null;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "id",
            "baseName": "id",
            "type": "string"
        },
        {
            "name": "remote_id",
            "baseName": "remote_id",
            "type": "string"
        },
        {
            "name": "name",
            "baseName": "name",
            "type": "string"
        },
        {
            "name": "description",
            "baseName": "description",
            "type": "string"
        },
        {
            "name": "amount",
            "baseName": "amount",
            "type": "number"
        },
        {
            "name": "owner",
            "baseName": "owner",
            "type": "string"
        },
        {
            "name": "account",
            "baseName": "account",
            "type": "string"
        },
        {
            "name": "stage",
            "baseName": "stage",
            "type": "string"
        },
        {
            "name": "status",
            "baseName": "status",
            "type": "OpportunityStatusEnum"
        },
        {
            "name": "last_activity_at",
            "baseName": "last_activity_at",
            "type": "Date"
        },
        {
            "name": "close_date",
            "baseName": "close_date",
            "type": "Date"
        },
        {
            "name": "remote_created_at",
            "baseName": "remote_created_at",
            "type": "Date"
        },
        {
            "name": "remote_data",
            "baseName": "remote_data",
            "type": "Array<RemoteData>"
        }    ];

    static getAttributeTypeMap() {
        return Opportunity.attributeTypeMap;
    }
}

