/* tslint:disable */
/* eslint-disable */
/**
 * Merge CRM API
 * The unified API for building rich integrations with multiple CRM platforms.
 *
 * The version of the OpenAPI document: 1.0
 * Contact: hello@merge.dev
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../../runtime';
import {
    CRMCustomObjectEndpointRequest,
    CRMCustomObjectEndpointRequestFromJSON,
    CRMCustomObjectEndpointRequestToJSON,
    CRMCustomObjectResponse,
    CRMCustomObjectResponseFromJSON,
    CRMCustomObjectResponseToJSON,
    CustomObject,
    CustomObjectFromJSON,
    CustomObjectToJSON,
    MetaResponse,
    MetaResponseFromJSON,
    MetaResponseToJSON,
    
    PatchedCRMCustomObjectEndpointRequest,
    PatchedCRMCustomObjectEndpointRequestFromJSON,
    PatchedCRMCustomObjectEndpointRequestToJSON,
} from '../models';
import {
	MergePaginatedResponse,
	MergePaginatedResponseFromJSON,
	MergePaginatedResponseToJSON,
} from '../../merge_paginated_response';

import {
    MergeMetaRequest
} from '../../merge_meta_request';

export interface CustomObjectClassesCustomObjectsCreateRequest {
    xAccountToken: string;
    customObjectClassId: string;
    cRMCustomObjectEndpointRequest: CRMCustomObjectEndpointRequest;
    isDebugMode?: boolean;
    runAsync?: boolean;
}

export interface CustomObjectClassesCustomObjectsListRequest {
    xAccountToken: string;
    customObjectClassId: string;
    createdAfter?: Date;
    createdBefore?: Date;
    cursor?: string;
    includeDeletedData?: boolean;
    includeRemoteData?: boolean;
    includeRemoteFields?: boolean;
    modifiedAfter?: Date;
    modifiedBefore?: Date;
    pageSize?: number;
    remoteId?: string | null;
}

export interface CustomObjectClassesCustomObjectsMetaPatchRetrieveRequest extends MergeMetaRequest {
    xAccountToken: string;
    customObjectClassId: string;
    id: string;
}

export interface CustomObjectClassesCustomObjectsMetaPostRetrieveRequest extends MergeMetaRequest {
    xAccountToken: string;
    customObjectClassId: string;
}

export interface CustomObjectClassesCustomObjectsPartialUpdateRequest {
    xAccountToken: string;
    customObjectClassId: string;
    id: string;
    patchedCRMCustomObjectEndpointRequest: PatchedCRMCustomObjectEndpointRequest;
    isDebugMode?: boolean;
    runAsync?: boolean;
}

export interface CustomObjectClassesCustomObjectsRetrieveRequest {
    xAccountToken: string;
    customObjectClassId: string;
    id: string;
    includeRemoteData?: boolean;
    includeRemoteFields?: boolean;
}

/**
 * 
 */
export class CustomObjectsApi extends runtime.BaseAPI {

    /**
     * Creates a `CustomObject` object with the given values.
     */
    async customObjectClassesCustomObjectsCreateRaw(requestParameters: CustomObjectClassesCustomObjectsCreateRequest): Promise<runtime.ApiResponse<CRMCustomObjectResponse | undefined>> {
        if (requestParameters.xAccountToken === null || requestParameters.xAccountToken === undefined) {
            throw new runtime.RequiredError('xAccountToken','Required parameter requestParameters.xAccountToken was null or undefined when calling customObjectClassesCustomObjectsCreate.');
        }

        if (requestParameters.customObjectClassId === null || requestParameters.customObjectClassId === undefined) {
            throw new runtime.RequiredError('customObjectClassId','Required parameter requestParameters.customObjectClassId was null or undefined when calling customObjectClassesCustomObjectsCreate.');
        }

        if (requestParameters.cRMCustomObjectEndpointRequest === null || requestParameters.cRMCustomObjectEndpointRequest === undefined) {
            throw new runtime.RequiredError('cRMCustomObjectEndpointRequest','Required parameter requestParameters.cRMCustomObjectEndpointRequest was null or undefined when calling customObjectClassesCustomObjectsCreate.');
        }

        const queryParameters: any = {};

        if (requestParameters.isDebugMode !== undefined) {
            queryParameters['is_debug_mode'] = requestParameters.isDebugMode;
        }

        if (requestParameters.runAsync !== undefined) {
            queryParameters['run_async'] = requestParameters.runAsync;
        }


        

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (requestParameters.xAccountToken !== undefined && requestParameters.xAccountToken !== null) {
            headerParameters['X-Account-Token'] = String(requestParameters.xAccountToken);
        }



        if (this.configuration && this.configuration.apiKey) {
            headerParameters["Authorization"] = `Bearer ${this.configuration.apiKey}`;
        }

        const response = await this.request({
            path: `/crm/v1/custom-object-classes/{custom_object_class_id}/custom-objects`.replace(`{${"custom_object_class_id"}}`, encodeURIComponent(String(requestParameters.customObjectClassId))),
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: CRMCustomObjectEndpointRequestToJSON(requestParameters.cRMCustomObjectEndpointRequest),
        });

        return new runtime.JSONApiResponse(response, (jsonValue) => CRMCustomObjectResponseFromJSON(jsonValue));
    }

    /**
     * Creates a `CustomObject` object with the given values.
     */
    async customObjectClassesCustomObjectsCreate(requestParameters: CustomObjectClassesCustomObjectsCreateRequest): Promise<CRMCustomObjectResponse | undefined> {
        const response = await this.customObjectClassesCustomObjectsCreateRaw(requestParameters);
        return await response.value();
    }

    /**
     * Returns a list of `CustomObject` objects.
     */
    async customObjectClassesCustomObjectsListRaw(requestParameters: CustomObjectClassesCustomObjectsListRequest): Promise<runtime.ApiResponse<MergePaginatedResponse<CustomObject> | undefined>> {
        if (requestParameters.xAccountToken === null || requestParameters.xAccountToken === undefined) {
            throw new runtime.RequiredError('xAccountToken','Required parameter requestParameters.xAccountToken was null or undefined when calling customObjectClassesCustomObjectsList.');
        }

        if (requestParameters.customObjectClassId === null || requestParameters.customObjectClassId === undefined) {
            throw new runtime.RequiredError('customObjectClassId','Required parameter requestParameters.customObjectClassId was null or undefined when calling customObjectClassesCustomObjectsList.');
        }

        const queryParameters: any = {};

        if (requestParameters.createdAfter !== undefined) {
            queryParameters['created_after'] = (requestParameters.createdAfter as any).toISOString();
        }

        if (requestParameters.createdBefore !== undefined) {
            queryParameters['created_before'] = (requestParameters.createdBefore as any).toISOString();
        }

        if (requestParameters.cursor !== undefined) {
            queryParameters['cursor'] = requestParameters.cursor;
        }

        if (requestParameters.includeDeletedData !== undefined) {
            queryParameters['include_deleted_data'] = requestParameters.includeDeletedData;
        }

        if (requestParameters.includeRemoteData !== undefined) {
            queryParameters['include_remote_data'] = requestParameters.includeRemoteData;
        }

        if (requestParameters.includeRemoteFields !== undefined) {
            queryParameters['include_remote_fields'] = requestParameters.includeRemoteFields;
        }

        if (requestParameters.modifiedAfter !== undefined) {
            queryParameters['modified_after'] = (requestParameters.modifiedAfter as any).toISOString();
        }

        if (requestParameters.modifiedBefore !== undefined) {
            queryParameters['modified_before'] = (requestParameters.modifiedBefore as any).toISOString();
        }

        if (requestParameters.pageSize !== undefined) {
            queryParameters['page_size'] = requestParameters.pageSize;
        }

        if (requestParameters.remoteId !== undefined) {
            queryParameters['remote_id'] = requestParameters.remoteId;
        }


        

        const headerParameters: runtime.HTTPHeaders = {};

        if (requestParameters.xAccountToken !== undefined && requestParameters.xAccountToken !== null) {
            headerParameters['X-Account-Token'] = String(requestParameters.xAccountToken);
        }



        if (this.configuration && this.configuration.apiKey) {
            headerParameters["Authorization"] = `Bearer ${this.configuration.apiKey}`;
        }

        const response = await this.request({
            path: `/crm/v1/custom-object-classes/{custom_object_class_id}/custom-objects`.replace(`{${"custom_object_class_id"}}`, encodeURIComponent(String(requestParameters.customObjectClassId))),
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        });

        return new runtime.JSONApiResponse(response, (jsonValue) => MergePaginatedResponseFromJSON(jsonValue, CustomObjectFromJSON));
    }

    /**
     * Returns a list of `CustomObject` objects.
     */
    async customObjectClassesCustomObjectsList(requestParameters: CustomObjectClassesCustomObjectsListRequest): Promise<MergePaginatedResponse<CustomObject> | undefined> {
        const response = await this.customObjectClassesCustomObjectsListRaw(requestParameters);
        return await response.value();
    }

    /**
     * Returns metadata for `CRMCustomObject` PATCHs.
     */
    async customObjectClassesCustomObjectsMetaPatchRetrieveRaw(requestParameters: CustomObjectClassesCustomObjectsMetaPatchRetrieveRequest): Promise<runtime.ApiResponse<MetaResponse | undefined>> {
        if (requestParameters.xAccountToken === null || requestParameters.xAccountToken === undefined) {
            throw new runtime.RequiredError('xAccountToken','Required parameter requestParameters.xAccountToken was null or undefined when calling customObjectClassesCustomObjectsMetaPatchRetrieve.');
        }

        if (requestParameters.customObjectClassId === null || requestParameters.customObjectClassId === undefined) {
            throw new runtime.RequiredError('customObjectClassId','Required parameter requestParameters.customObjectClassId was null or undefined when calling customObjectClassesCustomObjectsMetaPatchRetrieve.');
        }

        if (requestParameters.id === null || requestParameters.id === undefined) {
            throw new runtime.RequiredError('id','Required parameter requestParameters.id was null or undefined when calling customObjectClassesCustomObjectsMetaPatchRetrieve.');
        }

        const queryParameters: any = {};


        if (requestParameters !== undefined) {
            Object.keys(requestParameters.misc_params_query).forEach((key) => {
                if (requestParameters.misc_params_query[key] !== undefined) {
                    queryParameters[key] = requestParameters.misc_params_query[key];
                }
            })
        }
        

        const headerParameters: runtime.HTTPHeaders = {};

        if (requestParameters.xAccountToken !== undefined && requestParameters.xAccountToken !== null) {
            headerParameters['X-Account-Token'] = String(requestParameters.xAccountToken);
        }



        if (this.configuration && this.configuration.apiKey) {
            headerParameters["Authorization"] = `Bearer ${this.configuration.apiKey}`;
        }

        const response = await this.request({
            path: `/crm/v1/custom-object-classes/{custom_object_class_id}/custom-objects/meta/patch/{id}`.replace(`{${"custom_object_class_id"}}`, encodeURIComponent(String(requestParameters.customObjectClassId))).replace(`{${"id"}}`, encodeURIComponent(String(requestParameters.id))),
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        });

        return new runtime.JSONApiResponse(response, (jsonValue) => MetaResponseFromJSON(jsonValue));
    }

    /**
     * Returns metadata for `CRMCustomObject` PATCHs.
     */
    async customObjectClassesCustomObjectsMetaPatchRetrieve(requestParameters: CustomObjectClassesCustomObjectsMetaPatchRetrieveRequest): Promise<MetaResponse | undefined> {
        const response = await this.customObjectClassesCustomObjectsMetaPatchRetrieveRaw(requestParameters);
        return await response.value();
    }

    /**
     * Returns metadata for `CRMCustomObject` POSTs.
     */
    async customObjectClassesCustomObjectsMetaPostRetrieveRaw(requestParameters: CustomObjectClassesCustomObjectsMetaPostRetrieveRequest): Promise<runtime.ApiResponse<MetaResponse | undefined>> {
        if (requestParameters.xAccountToken === null || requestParameters.xAccountToken === undefined) {
            throw new runtime.RequiredError('xAccountToken','Required parameter requestParameters.xAccountToken was null or undefined when calling customObjectClassesCustomObjectsMetaPostRetrieve.');
        }

        if (requestParameters.customObjectClassId === null || requestParameters.customObjectClassId === undefined) {
            throw new runtime.RequiredError('customObjectClassId','Required parameter requestParameters.customObjectClassId was null or undefined when calling customObjectClassesCustomObjectsMetaPostRetrieve.');
        }

        const queryParameters: any = {};


        if (requestParameters !== undefined) {
            Object.keys(requestParameters.misc_params_query).forEach((key) => {
                if (requestParameters.misc_params_query[key] !== undefined) {
                    queryParameters[key] = requestParameters.misc_params_query[key];
                }
            })
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (requestParameters.xAccountToken !== undefined && requestParameters.xAccountToken !== null) {
            headerParameters['X-Account-Token'] = String(requestParameters.xAccountToken);
        }



        if (this.configuration && this.configuration.apiKey) {
            headerParameters["Authorization"] = `Bearer ${this.configuration.apiKey}`;
        }

        const response = await this.request({
            path: `/crm/v1/custom-object-classes/{custom_object_class_id}/custom-objects/meta/post`.replace(`{${"custom_object_class_id"}}`, encodeURIComponent(String(requestParameters.customObjectClassId))),
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        });

        return new runtime.JSONApiResponse(response, (jsonValue) => MetaResponseFromJSON(jsonValue));
    }

    /**
     * Returns metadata for `CRMCustomObject` POSTs.
     */
    async customObjectClassesCustomObjectsMetaPostRetrieve(requestParameters: CustomObjectClassesCustomObjectsMetaPostRetrieveRequest): Promise<MetaResponse | undefined> {
        const response = await this.customObjectClassesCustomObjectsMetaPostRetrieveRaw(requestParameters);
        return await response.value();
    }

    /**
     * Updates a `CustomObject` object with the given `id`.
     */
    async customObjectClassesCustomObjectsPartialUpdateRaw(requestParameters: CustomObjectClassesCustomObjectsPartialUpdateRequest): Promise<runtime.ApiResponse<CRMCustomObjectResponse | undefined>> {
        if (requestParameters.xAccountToken === null || requestParameters.xAccountToken === undefined) {
            throw new runtime.RequiredError('xAccountToken','Required parameter requestParameters.xAccountToken was null or undefined when calling customObjectClassesCustomObjectsPartialUpdate.');
        }

        if (requestParameters.customObjectClassId === null || requestParameters.customObjectClassId === undefined) {
            throw new runtime.RequiredError('customObjectClassId','Required parameter requestParameters.customObjectClassId was null or undefined when calling customObjectClassesCustomObjectsPartialUpdate.');
        }

        if (requestParameters.id === null || requestParameters.id === undefined) {
            throw new runtime.RequiredError('id','Required parameter requestParameters.id was null or undefined when calling customObjectClassesCustomObjectsPartialUpdate.');
        }

        if (requestParameters.patchedCRMCustomObjectEndpointRequest === null || requestParameters.patchedCRMCustomObjectEndpointRequest === undefined) {
            throw new runtime.RequiredError('patchedCRMCustomObjectEndpointRequest','Required parameter requestParameters.patchedCRMCustomObjectEndpointRequest was null or undefined when calling customObjectClassesCustomObjectsPartialUpdate.');
        }

        const queryParameters: any = {};

        if (requestParameters.isDebugMode !== undefined) {
            queryParameters['is_debug_mode'] = requestParameters.isDebugMode;
        }

        if (requestParameters.runAsync !== undefined) {
            queryParameters['run_async'] = requestParameters.runAsync;
        }


        

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (requestParameters.xAccountToken !== undefined && requestParameters.xAccountToken !== null) {
            headerParameters['X-Account-Token'] = String(requestParameters.xAccountToken);
        }



        if (this.configuration && this.configuration.apiKey) {
            headerParameters["Authorization"] = `Bearer ${this.configuration.apiKey}`;
        }

        const response = await this.request({
            path: `/crm/v1/custom-object-classes/{custom_object_class_id}/custom-objects/{id}`.replace(`{${"custom_object_class_id"}}`, encodeURIComponent(String(requestParameters.customObjectClassId))).replace(`{${"id"}}`, encodeURIComponent(String(requestParameters.id))),
            method: 'PATCH',
            headers: headerParameters,
            query: queryParameters,
            body: PatchedCRMCustomObjectEndpointRequestToJSON(requestParameters.patchedCRMCustomObjectEndpointRequest),
        });

        return new runtime.JSONApiResponse(response, (jsonValue) => CRMCustomObjectResponseFromJSON(jsonValue));
    }

    /**
     * Updates a `CustomObject` object with the given `id`.
     */
    async customObjectClassesCustomObjectsPartialUpdate(requestParameters: CustomObjectClassesCustomObjectsPartialUpdateRequest): Promise<CRMCustomObjectResponse | undefined> {
        const response = await this.customObjectClassesCustomObjectsPartialUpdateRaw(requestParameters);
        return await response.value();
    }

    /**
     * Returns a `CustomObject` object with the given `id`.
     */
    async customObjectClassesCustomObjectsRetrieveRaw(requestParameters: CustomObjectClassesCustomObjectsRetrieveRequest): Promise<runtime.ApiResponse<CustomObject | undefined>> {
        if (requestParameters.xAccountToken === null || requestParameters.xAccountToken === undefined) {
            throw new runtime.RequiredError('xAccountToken','Required parameter requestParameters.xAccountToken was null or undefined when calling customObjectClassesCustomObjectsRetrieve.');
        }

        if (requestParameters.customObjectClassId === null || requestParameters.customObjectClassId === undefined) {
            throw new runtime.RequiredError('customObjectClassId','Required parameter requestParameters.customObjectClassId was null or undefined when calling customObjectClassesCustomObjectsRetrieve.');
        }

        if (requestParameters.id === null || requestParameters.id === undefined) {
            throw new runtime.RequiredError('id','Required parameter requestParameters.id was null or undefined when calling customObjectClassesCustomObjectsRetrieve.');
        }

        const queryParameters: any = {};

        if (requestParameters.includeRemoteData !== undefined) {
            queryParameters['include_remote_data'] = requestParameters.includeRemoteData;
        }

        if (requestParameters.includeRemoteFields !== undefined) {
            queryParameters['include_remote_fields'] = requestParameters.includeRemoteFields;
        }


        

        const headerParameters: runtime.HTTPHeaders = {};

        if (requestParameters.xAccountToken !== undefined && requestParameters.xAccountToken !== null) {
            headerParameters['X-Account-Token'] = String(requestParameters.xAccountToken);
        }



        if (this.configuration && this.configuration.apiKey) {
            headerParameters["Authorization"] = `Bearer ${this.configuration.apiKey}`;
        }

        const response = await this.request({
            path: `/crm/v1/custom-object-classes/{custom_object_class_id}/custom-objects/{id}`.replace(`{${"custom_object_class_id"}}`, encodeURIComponent(String(requestParameters.customObjectClassId))).replace(`{${"id"}}`, encodeURIComponent(String(requestParameters.id))),
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        });

        return new runtime.JSONApiResponse(response, (jsonValue) => CustomObjectFromJSON(jsonValue));
    }

    /**
     * Returns a `CustomObject` object with the given `id`.
     */
    async customObjectClassesCustomObjectsRetrieve(requestParameters: CustomObjectClassesCustomObjectsRetrieveRequest): Promise<CustomObject | undefined> {
        const response = await this.customObjectClassesCustomObjectsRetrieveRaw(requestParameters);
        return await response.value();
    }

}
