/* tslint:disable */
/* eslint-disable */
/**
 * Merge ATS API
 * The unified API for building rich integrations with multiple Applicant Tracking System platforms.
 *
 * The version of the OpenAPI document: 1.0
 * Contact: hello@merge.dev
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../../runtime';
import { JSONValue } from '../../merge_json';
import {
    ActivityRequest,
    ActivityRequestFromJSON,
    ActivityRequestFromJSONTyped,
    ActivityRequestToJSON,
} from './';


/**
 * 
 * @export
 * @interface ActivityEndpointRequest
 */
export interface ActivityEndpointRequest {
    /**
     * 
     * @type {ActivityRequest}
     * @memberof ActivityEndpointRequest
     */
    model: ActivityRequest;
    /**
     * 
     * @type {string}
     * @memberof ActivityEndpointRequest
     */
    remote_user_id: string;
}

export function ActivityEndpointRequestFromJSON(json: JSONValue): ActivityEndpointRequest | undefined {
    return ActivityEndpointRequestFromJSONTyped(json);
}

export function ActivityEndpointRequestFromJSONTyped(json: JSONValue): ActivityEndpointRequest | undefined {
    if ((json === undefined) || (json === null)) {
        return undefined;
    }

    return {
        
        'model': ActivityRequestFromJSON(json['model']) as ActivityRequest,
        'remote_user_id': json['remote_user_id'],
    };
}

export function ActivityEndpointRequestToJSON(value?: ActivityEndpointRequest): JSONValue {
    if (value === undefined || value === null) {
        return undefined;
    }

    return {
        
        'model': ActivityRequestToJSON(value.model),
        'remote_user_id': value.remote_user_id,
    };
}

