/* tslint:disable */
/* eslint-disable */
/**
 * Merge ATS API
 * The unified API for building rich integrations with multiple Applicant Tracking System platforms.
 *
 * The version of the OpenAPI document: 1.0
 * Contact: hello@merge.dev
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../../runtime';
import { JSONValue } from '../../merge_json';
import {
    EmailAddressTypeEnum,
    EmailAddressTypeEnumFromJSON,
    EmailAddressTypeEnumFromJSONTyped,
    EmailAddressTypeEnumToJSON,
} from './';


/**
 * # The EmailAddress Object
 * ### Description
 * The `EmailAddress` object is used to represent a candidate's email address.
 * ### Usage Example
 * Fetch from the `GET Candidate` endpoint and view their email addresses.
 * @export
 * @interface EmailAddress
 */
export interface EmailAddress {
    /**
     * The email address.
     * @type {string}
     * @memberof EmailAddress
     */
    value?: string | null;
    /**
     * The type of email address.
     * @type {EmailAddressTypeEnum}
     * @memberof EmailAddress
     */
    email_address_type?: EmailAddressTypeEnum | null;
}

export function EmailAddressFromJSON(json: JSONValue): EmailAddress | null {
    return EmailAddressFromJSONTyped(json);
}

export function EmailAddressFromJSONTyped(json: JSONValue): EmailAddress | null {
    if ((json === undefined) || (json === null)) {
        return null;
    }

    return {
        
        'value': !exists(json, 'value') ? undefined : json['value'],
        'email_address_type': !exists(json, 'email_address_type') ? undefined : EmailAddressTypeEnumFromJSON(json['email_address_type']),
    };
}

export function EmailAddressToJSON(value?: EmailAddress): JSONValue {
    if (value === undefined || value === null) {
        return null;
    }

    return {
        
        'value': value.value,
        'email_address_type': EmailAddressTypeEnumToJSON(value.email_address_type),
    };
}

