/* tslint:disable */
/* eslint-disable */
/**
 * Merge ATS API
 * The unified API for building rich integrations with multiple Applicant Tracking System platforms.
 *
 * The version of the OpenAPI document: 1.0
 * Contact: hello@merge.dev
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import { JSONValue } from '../../merge_json'
import {
    EEOC,
    EEOCFromJSON,
    EEOCFromJSONTyped,
    EEOCToJSON,
} from './';


/**
 * 
 * @export
 * @interface PaginatedEEOCList
 */
export interface PaginatedEEOCList {
    /**
     * 
     * @type {string}
     * @memberof PaginatedEEOCList
     */
    next?: string | null;
    /**
     * 
     * @type {string}
     * @memberof PaginatedEEOCList
     */
    previous?: string | null;
    /**
     * 
     * @type {Array<EEOC>}
     * @memberof PaginatedEEOCList
     */
    results?: Array<EEOC>;
}

export function PaginatedEEOCListFromJSON(json: JSONValue): PaginatedEEOCList {
    return PaginatedEEOCListFromJSONTyped(json);
}

export function PaginatedEEOCListFromJSONTyped(json: JSONValue): PaginatedEEOCList {
    if ((json === undefined) || (json === null)) {
        return json;
    }

    return {
        
        'next': !exists(json, 'next') ? undefined : json['next'],
        'previous': !exists(json, 'previous') ? undefined : json['previous'],
        'results': !exists(json, 'results') ? undefined : ((json['results'] as Array<any>).map(EEOCFromJSON)),
    };
}

export function PaginatedEEOCListToJSON(value?: PaginatedEEOCList | null): JSONValue {
    if (value === undefined || value === null) {
        return value;
    }

    return {
        
        'next': value.next,
        'previous': value.previous,
        'results': value.results === undefined ? undefined : ((value.results as Array<any>).map(EEOCToJSON)),
    };
}

