/* tslint:disable */
/* eslint-disable */
/**
 * Merge ATS API
 * The unified API for building rich integrations with multiple Applicant Tracking System platforms.
 *
 * The version of the OpenAPI document: 1.0
 * Contact: hello@merge.dev
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { JSONValue } from "../../merge_json";

/**
 * 
 * @export
 * @enum {string}
 */
export enum ScheduledInterviewStatusEnumValues {
    MERGE_NONSTANDARD_VALUE = 'MERGE_NONSTANDARD_VALUE',
    Scheduled = 'SCHEDULED',
    AwaitingFeedback = 'AWAITING_FEEDBACK',
    Complete = 'COMPLETE'
}

export interface ScheduledInterviewStatusEnum {
    value: ScheduledInterviewStatusEnumValues,
    rawValue: string
}


export function ScheduledInterviewStatusEnumFromJSON(json: any): ScheduledInterviewStatusEnum {
    return ScheduledInterviewStatusEnumFromJSONTyped(json, false);
}

export function ScheduledInterviewStatusEnumFromJSONTyped(json: any, ignoreDiscriminator: boolean): ScheduledInterviewStatusEnum {
    if ((<any>Object).values(ScheduledInterviewStatusEnumValues).includes(json)) {
        return {
            value: json as ScheduledInterviewStatusEnumValues,
            rawValue: json as string
        }
    }
    return {
        value: ScheduledInterviewStatusEnumValues.MERGE_NONSTANDARD_VALUE,
        rawValue: json as string
    }
}

export function ScheduledInterviewStatusEnumToJSON(value?: ScheduledInterviewStatusEnum | null): JSONValue {
    return value && value.value != ScheduledInterviewStatusEnumValues.MERGE_NONSTANDARD_VALUE ? value.value as string : null;
}

