/* tslint:disable */
/* eslint-disable */
/**
 * Merge ATS API
 * The unified API for building rich integrations with multiple Applicant Tracking System platforms.
 *
 * The version of the OpenAPI document: 1.0
 * Contact: hello@merge.dev
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { JSONValue } from "../../merge_json";

/**
 * 
 * @export
 * @enum {string}
 */
export enum UrlTypeEnum {
    MERGE_NONSTANDARD_VALUE = 'MERGE_NONSTANDARD_VALUE',
    Personal = 'PERSONAL',
    Company = 'COMPANY',
    Portfolio = 'PORTFOLIO',
    Blog = 'BLOG',
    SocialMedia = 'SOCIAL_MEDIA',
    Other = 'OTHER',
    JobPosting = 'JOB_POSTING'
}


export function UrlTypeEnumFromJSON(json: any): UrlTypeEnum {
    return UrlTypeEnumFromJSONTyped(json, false);
}

export function UrlTypeEnumFromJSONTyped(json: any, ignoreDiscriminator: boolean): UrlTypeEnum {
    if ((<any>Object).values(UrlTypeEnum).includes(json)) {
        return json as UrlTypeEnum;
    }
    return UrlTypeEnum.MERGE_NONSTANDARD_VALUE;
}

export function UrlTypeEnumToJSON(value?: UrlTypeEnum | null): JSONValue {
    return value ? value as string : null;
}

