/* tslint:disable */
/* eslint-disable */
/**
 * Merge CRM API
 * The unified API for building rich integrations with multiple CRM platforms.
 *
 * The version of the OpenAPI document: 1.0
 * Contact: hello@merge.dev
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from './runtime';
import { JSONValue } from './merge_json'

/**
 * 
 * @export
 * @interface MergePaginatedResponse
 */
export interface MergePaginatedResponse<T> {
    /**
     * 
     * @type {string}
     * @memberof MergePaginatedResponse
     */
    next?: string | null;
    /**
     * 
     * @type {string}
     * @memberof MergePaginatedResponse
     */
    previous?: string | null;
    /**
     * 
     * @type {Array<T>}
     * @memberof MergePaginatedResponse
     */
    results?: Array<T>;
}

export function MergePaginatedResponseFromJSON<T>(json: JSONValue): MergePaginatedResponse<T> | null {
    return MergePaginatedResponseFromJSONTyped(json);
}

export function MergePaginatedResponseFromJSONTyped<T>(json: JSONValue): MergePaginatedResponse<T> | null {
    if ((json === undefined) || (json === null)) {
        return null;
    }

    return {
        
        'next': !exists(json, 'next') ? undefined : json['next'],
        'previous': !exists(json, 'previous') ? undefined : json['previous'],
        'results': !exists(json, 'results') ? undefined : ((json['results'] as Array<T>)),
    };
}

export function MergePaginatedResponseToJSON<T extends JSONValue>(value?: MergePaginatedResponse<T>): JSONValue {
    if (value === undefined || value === null) {
        return null;
    }

    return {
        
        'next': value.next,
        'previous': value.previous,
        'results': value.results === undefined ? undefined : ((value.results as Array<JSONValue>)),
    };
}

