/* tslint:disable */
/* eslint-disable */
/**
 * Merge HRIS API
 * The unified API for building rich integrations with multiple HR Information System platforms.
 *
 * The version of the OpenAPI document: 1.0
 * Contact: hello@merge.dev
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { JSONValue } from "../../merge_json";

/**
 * 
 * @export
 * @enum {string}
 */
export enum AccountTypeEnum {
    MERGE_NONSTANDARD_VALUE = 'MERGE_NONSTANDARD_VALUE',
    Savings = 'SAVINGS',
    Checking = 'CHECKING'
}


export function AccountTypeEnumFromJSON(json: any): AccountTypeEnum {
    return AccountTypeEnumFromJSONTyped(json, false);
}

export function AccountTypeEnumFromJSONTyped(json: any, ignoreDiscriminator: boolean): AccountTypeEnum {
    if ((<any>Object).values(AccountTypeEnum).includes(json)) {
        return json as AccountTypeEnum;
    }
    return AccountTypeEnum.MERGE_NONSTANDARD_VALUE;
}

export function AccountTypeEnumToJSON(value?: AccountTypeEnum | null): JSONValue {
    return value ? value as string : null;
}

