/* tslint:disable */
/* eslint-disable */
/**
 * Merge HRIS API
 * The unified API for building rich integrations with multiple HR Information System platforms.
 *
 * The version of the OpenAPI document: 1.0
 * Contact: hello@merge.dev
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * 
 * @export
 * @enum {string}
 */
export enum EmploymentTypeEnum {
    FullTime = 'FULL_TIME',
    PartTime = 'PART_TIME',
    Intern = 'INTERN',
    Contractor = 'CONTRACTOR',
    Freelance = 'FREELANCE'
}

export function EmploymentTypeEnumFromJSON(json: any): EmploymentTypeEnum {
    return EmploymentTypeEnumFromJSONTyped(json, false);
}

export function EmploymentTypeEnumFromJSONTyped(json: any, ignoreDiscriminator: boolean): EmploymentTypeEnum {
    return json as EmploymentTypeEnum;
}

export function EmploymentTypeEnumToJSON(value?: EmploymentTypeEnum | null): any {
    return value as any;
}

