/* tslint:disable */
/* eslint-disable */
/**
 * Merge HRIS API
 * The unified API for building rich integrations with multiple HR Information System platforms.
 *
 * The version of the OpenAPI document: 1.0
 * Contact: hello@merge.dev
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../../runtime';
import { JSONValue } from '../../merge_json';
import {
    ReasonEnum,
    ReasonEnumFromJSON,
    ReasonEnumFromJSONTyped,
    ReasonEnumToJSON,
} from './';


/**
 * 
 * @export
 * @interface IgnoreCommonModel
 */
export interface IgnoreCommonModel {
    /**
     * 
     * @type {ReasonEnum}
     * @memberof IgnoreCommonModel
     */
    reason: ReasonEnum;
    /**
     * 
     * @type {string}
     * @memberof IgnoreCommonModel
     */
    message?: string;
}

export function IgnoreCommonModelFromJSON(json: JSONValue): IgnoreCommonModel | null {
    return IgnoreCommonModelFromJSONTyped(json);
}

export function IgnoreCommonModelFromJSONTyped(json: JSONValue): IgnoreCommonModel | null {
    if ((json === undefined) || (json === null)) {
        return null;
    }

    return {
        
        'reason': ReasonEnumFromJSON(json['reason']),
        'message': !exists(json, 'message') ? undefined : json['message'],
    };
}

export function IgnoreCommonModelToJSON(value?: IgnoreCommonModel): JSONValue {
    if (value === undefined || value === null) {
        return null;
    }

    return {
        
        'reason': ReasonEnumToJSON(value.reason),
        'message': value.message,
    };
}

