/* tslint:disable */
/* eslint-disable */
/**
 * Merge HRIS API
 * The unified API for building rich integrations with multiple HR Information System platforms.
 *
 * The version of the OpenAPI document: 1.0
 * Contact: hello@merge.dev
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { JSONValue } from "../../merge_json";

/**
 * 
 * @export
 * @enum {string}
 */
export enum LocationTypeEnum {
    MERGE_NONSTANDARD_VALUE = 'MERGE_NONSTANDARD_VALUE',
    Home = 'HOME',
    Work = 'WORK'
}


export function LocationTypeEnumFromJSON(json: any): LocationTypeEnum {
    return LocationTypeEnumFromJSONTyped(json, false);
}

export function LocationTypeEnumFromJSONTyped(json: any, ignoreDiscriminator: boolean): LocationTypeEnum {
    if ((<any>Object).values(LocationTypeEnum).includes(json)) {
        return json as LocationTypeEnum;
    }
    return LocationTypeEnum.MERGE_NONSTANDARD_VALUE;
}

export function LocationTypeEnumToJSON(value?: LocationTypeEnum | null): JSONValue {
    return value ? value as string : null;
}

