/* tslint:disable */
/* eslint-disable */
/**
 * Merge HRIS API
 * The unified API for building rich integrations with multiple HR Information System platforms.
 *
 * The version of the OpenAPI document: 1.0
 * Contact: hello@merge.dev
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { JSONValue } from "../../merge_json";

/**
 * 
 * @export
 * @enum {string}
 */
export enum MaritalStatusEnumValues {
    MERGE_NONSTANDARD_VALUE = 'MERGE_NONSTANDARD_VALUE',
    Single = 'SINGLE',
    MarriedFilingJointly = 'MARRIED_FILING_JOINTLY',
    MarriedFilingSeparately = 'MARRIED_FILING_SEPARATELY',
    HeadOfHousehold = 'HEAD_OF_HOUSEHOLD',
    QualifyingWidowOrWidowerWithDependentChild = 'QUALIFYING_WIDOW_OR_WIDOWER_WITH_DEPENDENT_CHILD'
}

export interface MaritalStatusEnum {
    value: MaritalStatusEnumValues,
    rawValue: string
}


export function MaritalStatusEnumFromJSON(json: any): MaritalStatusEnum {
    return MaritalStatusEnumFromJSONTyped(json, false);
}

export function MaritalStatusEnumFromJSONTyped(json: any, ignoreDiscriminator: boolean): MaritalStatusEnum {
    if ((<any>Object).values(MaritalStatusEnumValues).includes(json)) {
        return {
            value: json as MaritalStatusEnumValues,
            rawValue: json as string
        }
    }
    return {
        value: MaritalStatusEnumValues.MERGE_NONSTANDARD_VALUE,
        rawValue: json as string
    }
}

export function MaritalStatusEnumToJSON(value?: MaritalStatusEnum | null): JSONValue {
    return value && value.value != MaritalStatusEnumValues.MERGE_NONSTANDARD_VALUE ? value.value as string : null;
}

