name: Semgrep
on:
  # diff aware on every PR
  pull_request: {}
  # allow manual triggering
  workflow_dispatch: {}
  # full scan on push to master
  push:
    branches: ["main", "master"]
  # Full scan on every Monday at 12:30 UTC/8:30 ET
  schedule:
    - cron: "30 12 * * 1"
jobs:
  semgrep:
    name: semgrep/ci
    runs-on: ubuntu-latest

    container:
      image: returntocorp/semgrep

    # Skip any PR created by dependabot to avoid permission issues:
    if: (github.actor != 'dependabot[bot]')

    steps:
      - uses: actions/checkout@v3
      - run: semgrep ci
        env:
          SEMGREP_APP_TOKEN: ${{ secrets.SEMGREP_APP_TOKEN }}
